---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: github-actions-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: sa-github-actions
    namespace: example-helm
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
