apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 1313
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
