apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Chart.Name }}.claud.dev
    secretName: {{ .Chart.Name }}-tls
  rules:
  - host: {{ .Chart.Name }}.claud.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app.name }}
          servicePort: 80
