[[events]]
type       = "meetup"
name       = "Continuous Integration and Deployment For Documentation"
start_date = 2017-02-27T18:30:00-05:00
end_date   = 2017-02-27T19:45:00-05:00
location   = "New York, NY"
link       = "https://www.meetup.com/WriteTheDocsNYC/events/237540081/"

[[events]]
type       = "meetup"
name       = "Charting the English Language, in Pure Clojure"
start_date = 2016-11-16T00:00:00Z
end_date   = 2016-11-16T00:00:00Z
location   = "Philadelphia, PA"
link       = "https://www.meetup.com/Clojadelphia/events/235472275/"
